
os:
    - linux

language: cpp

compiler:
    - gcc

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    #- gcc-7
    #- g++-7
    - libboost-all-dev
    - libgsl0-dev
    
before_install:
    #- if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
    - sudo apt-add-repository ppa:j-4/vienna-rna -y
    - sudo apt-get update -q
    - sudo apt-get install vienna-rna -y
#    - sudo apt-get install vienna-rna-dev -y
#    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
#    - chmod +x miniconda.sh
#    - "./miniconda.sh -b -p ~/miniconda3"
#    - export CONDA_PATH=$HOME/miniconda3
#    - export PATH=$CONDA_PATH/bin:$PATH
#    - conda update --yes conda
#    - conda create -n build_env --yes "viennarna>=2.4.8" -c bioconda
#    - source activate build_env
#    - conda list
#    - export CONDA_LIB_PATH=$CONDA_PATH/envs/build_env/lib
#    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_LIB_PATH

script:
    - $CXX --version
    - which $CXX
    - RNAalifold --version
    ##### start IntaRNA build #####
    - cd $TRAVIS_BUILD_DIR 
    # generate autotools's files 
    - bash autotools-init.sh 
#    - ./configure --with-vrna=$CONDA_PATH --prefix=$HOME/IntaRNA
    - ./configure --prefix=$HOME/IntaRNA
    # compile documentation
    # - make doxygen-doc
    # compile, test and install IntaRNA
    - make -j 2 && make tests -j 2 && make install
    ##### check IntaRNA build #####
    # run IntaRNA with help output
    - $HOME/IntaRNA/bin/IntaRNA -h
