dist: trusty

language: cpp

compiler:
    - gcc

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    
install:
  # install conda to install build requirements
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b"
  - export CONDA_PATH=$HOME/miniconda3
  - export PATH=$CONDA_PATH/bin:$PATH
  - conda update --yes conda
  - conda create -n build-IntaRNA --yes -c bioconda gcc_linux-64 gxx_linux-64 boost-cpp viennarna pkgconfig
  - bash -l -c "conda init bash"
#  - conda activate build-IntaRNA

script:
#    - $CXX --version
#    - which $CXX
  #  - RNAalifold --version
    ##### start IntaRNA build #####
    - cd $TRAVIS_BUILD_DIR
    - bash -l -c ./build-IntaRNA-on-Travis.sh 
    # generate autotools's files 
#    - bash autotools-init.sh 
#    - ./configure --prefix=$HOME/IntaRNA --with-vrna=${CONDA_PATH}
    # compile documentation
    # - make doxygen-doc
    # compile, test and install IntaRNA
    - make -j 2 && make tests -j 2 && make install
    ##### check IntaRNA build #####
    # run IntaRNA with help output
    - $HOME/IntaRNA/bin/IntaRNA -h
