language: cpp

cache:
  apt: true

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev

os:
  - linux

compiler:
  - gcc
  
script:
 # download and compile ViennaRNA dependency
 - wget http://www.tbi.univie.ac.at/RNA/download/sourcecode/2_2_x/ViennaRNA-2.2.10.tar.gz
 - tar xvfz ViennaRNA-2.2.10.tar.gz
 - cd ViennaRNA-2.2.10 && ./configure --prefix=$HOME/vienna --without-doc --without-python --without-python3 --without-check --without-perl --without-swig --without-cluster --without-forester --without-kinfold --without-json --disable-unittests --without-kinwalker && make && make install
 # generate autotools's files and compile IntaRNA
 #- cd $TRAVIS_BUILD_DIR && bash autotools-init.sh && ./configure --enable-c11 --with-RNA=$HOME/vienna --prefix=$HOME/IntaRNA && make && make install
 # run IntaRNA
 #- $HOME/IntaRNA/bin/IntaRNA -h
