dist: trusty

language: minimal

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # create build environment
#  - conda create -q -n build-IntaRNA -c bioconda gcc_linux-64 gxx_linux-64 boost-cpp viennarna pkgconfig
#  - conda activate build-IntaRNA
  # install dependencies
  - conda install -c bioconda gcc_linux-64 gxx_linux-64 boost-cpp viennarna pkgconfig

script:
    ##### start IntaRNA build #####
    - cd $TRAVIS_BUILD_DIR
    # generate autotools's files 
    - bash autotools-init.sh 
    # run configure
    - ./configure --prefix=$HOME/IntaRNA --with-vrna=$HOME/miniconda/envs/build-IntaRNA --with-boost=no
    # compile documentation
    # - make doxygen-doc
    # compile, test and install IntaRNA
    - make -j 2 && make tests -j 2 && make install
    ##### check IntaRNA build #####
    # run IntaRNA with help output
    - $HOME/IntaRNA/bin/IntaRNA -h
